apiVersion: v1
kind: Pod
metadata:
  name: run-workflow
spec:
  containers:
  - name: argo
    image: ubuntu:latest
    command:
        - /bin/sh
        - -c
        - |
          apt-get update
          apt-get install git -y
          apt-get install curl -yy
          git clone https://github.com/SiyaAmonkar/argoworkflow.git
          curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.2/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          mv ./argo-linux-amd64 /usr/local/bin/argo
          argo list
          cd argoworkflow
          argo submit example.yaml
  restartPolicy: OnFailure
