apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay-template
    arguments:
      parameters:
      - name: message
        value: "from workflow"
    workflowTemplateRef:
      name: workflow-template-submittable
