apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testworkflow
  annotations:
    #argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  entrypoint: test-sync
  templates:
    - name: test-sync
      script:
        image: ubuntu:18.04
        command: [bash]
        source: | 
          apt-get update 
          apt-get install -y curl
          apt-get install -yy git
          curl -sLO https://github.com/argoproj/argo/releases/download/v3.1.0-rc11/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          mv ./argo-linux-amd64 /usr/local/bin/argo
          git clone https://github.com/SiyaAmonkar/ArgocdDemo.git
          cd ArgocdDemo
          argo list
          argo template lint templates
