apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: testworkflow
  #annotations:
    #argocd.argoproj.io/hook: PreSync
spec:
  entrypoint: test-sync
  templates:
    - name: test-sync
      script:
        image: ubuntu:18.04
        command: [bash]
        source: | 
          apt-get update 
          apt-get install -y curl
          curl -sLO https://github.com/argoproj/argo/releases/download/v3.1.0-rc11/argo-linux-amd64.gz
          gunzip argo-linux-amd64.gz
          chmod +x argo-linux-amd64
          mv ./argo-linux-amd64 /usr/local/bin/argo
          argo list
